// Mock data for admin back-office

export const mockAdminUsers = [
  {
    id: "usr_001",
    firstName: "Chidi",
    lastName: "Okonkwo",
    email: "chidi@example.com",
    phone: "+2348012345678",
    role: "TENANT" as const,
    bvnVerificationStatus: "VERIFIED" as const,
    ninVerificationStatus: "NOT_SUBMITTED" as const,
    idDocumentStatus: "VERIFIED" as const,
    trustScore: 75,
    isEmailVerified: true,
    isPhoneVerified: true,
    isActive: true,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-15"),
    profilePhoto: null,
  },
  {
    id: "usr_002",
    firstName: "Amaka",
    lastName: "Eze",
    email: "amaka@example.com",
    phone: "+2348098765432",
    role: "LANDLORD" as const,
    bvnVerificationStatus: "VERIFIED" as const,
    ninVerificationStatus: "PENDING" as const,
    idDocumentStatus: "VERIFIED" as const,
    trustScore: 90,
    isEmailVerified: true,
    isPhoneVerified: true,
    isActive: true,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2024-12-01"),
    profilePhoto: null,
  },
  {
    id: "usr_003",
    firstName: "Emeka",
    lastName: "Nwosu",
    email: "emeka@example.com",
    phone: "+2347033445566",
    role: "AGENT" as const,
    bvnVerificationStatus: "PENDING" as const,
    ninVerificationStatus: "NOT_SUBMITTED" as const,
    idDocumentStatus: "PENDING" as const,
    trustScore: 40,
    isEmailVerified: true,
    isPhoneVerified: false,
    isActive: true,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-01"),
    profilePhoto: null,
  },
  {
    id: "usr_004",
    firstName: "Ngozi",
    lastName: "Adeyemi",
    email: "ngozi@example.com",
    phone: "+2348056789012",
    role: "TENANT" as const,
    bvnVerificationStatus: "FAILED" as const,
    ninVerificationStatus: "NOT_SUBMITTED" as const,
    idDocumentStatus: "NOT_SUBMITTED" as const,
    trustScore: 10,
    isEmailVerified: true,
    isPhoneVerified: false,
    isActive: true,
    isBanned: false,
    onboardingComplete: false,
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
    profilePhoto: null,
  },
  {
    id: "usr_005",
    firstName: "Tunde",
    lastName: "Bakare",
    email: "tunde@example.com",
    phone: "+2348023456789",
    role: "LANDLORD" as const,
    bvnVerificationStatus: "VERIFIED" as const,
    ninVerificationStatus: "VERIFIED" as const,
    idDocumentStatus: "VERIFIED" as const,
    trustScore: 95,
    isEmailVerified: true,
    isPhoneVerified: true,
    isActive: false,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-11-20"),
    profilePhoto: null,
  },
  {
    id: "usr_006",
    firstName: "Fatima",
    lastName: "Ibrahim",
    email: "fatima@example.com",
    phone: "+2347012345678",
    role: "TENANT" as const,
    bvnVerificationStatus: "NOT_SUBMITTED" as const,
    ninVerificationStatus: "NOT_SUBMITTED" as const,
    idDocumentStatus: "NOT_SUBMITTED" as const,
    trustScore: 25,
    isEmailVerified: false,
    isPhoneVerified: true,
    isActive: true,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
    profilePhoto: null,
  },
  {
    id: "usr_007",
    firstName: "Kola",
    lastName: "Adeola",
    email: "kola@example.com",
    phone: "+2348077889900",
    role: "AGENT" as const,
    bvnVerificationStatus: "VERIFIED" as const,
    ninVerificationStatus: "VERIFIED" as const,
    idDocumentStatus: "VERIFIED" as const,
    trustScore: 85,
    isEmailVerified: true,
    isPhoneVerified: true,
    isActive: true,
    isBanned: false,
    onboardingComplete: true,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-12-01"),
    profilePhoto: null,
  },
  {
    id: "usr_008",
    firstName: "Blessing",
    lastName: "Osei",
    email: "blessing@example.com",
    phone: "+2348099887766",
    role: "TENANT" as const,
    bvnVerificationStatus: "NOT_SUBMITTED" as const,
    ninVerificationStatus: "NOT_SUBMITTED" as const,
    idDocumentStatus: "NOT_SUBMITTED" as const,
    trustScore: 0,
    isEmailVerified: false,
    isPhoneVerified: false,
    isActive: true,
    isBanned: true,
    onboardingComplete: false,
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2024-12-18"),
    profilePhoto: null,
  },
];

export const mockPendingListings = [
  {
    id: "lst_001",
    title: "3 Bedroom Flat in Lekki Phase 1",
    address: "12 Admiralty Road, Lekki Phase 1",
    area: "Lekki",
    lga: "Eti-Osa",
    state: "Lagos",
    propertyType: "FLAT" as const,
    bedrooms: 3,
    bathrooms: 2,
    annualRent: 350000000, // in kobo
    status: "PENDING_VERIFICATION" as const,
    isVerified: false,
    owner: mockAdminUsers[1],
    titleDocumentUrl: "/mock-title-doc.pdf",
    surveyPlanUrl: "/mock-survey.pdf",
    photos: [{ url: "/mock-property-1.jpg", order: 0 }],
    createdAt: new Date("2024-12-18"),
    viewCount: 0,
    enquiryCount: 0,
  },
  {
    id: "lst_002",
    title: "Self-Contained Studio in Victoria Island",
    address: "5 Akin Adesola Street, Victoria Island",
    area: "Victoria Island",
    lga: "Eti-Osa",
    state: "Lagos",
    propertyType: "STUDIO" as const,
    bedrooms: 1,
    bathrooms: 1,
    annualRent: 180000000,
    status: "PENDING_VERIFICATION" as const,
    isVerified: false,
    owner: mockAdminUsers[6],
    titleDocumentUrl: "/mock-title-doc.pdf",
    surveyPlanUrl: null,
    photos: [{ url: "/mock-property-2.jpg", order: 0 }],
    createdAt: new Date("2024-12-17"),
    viewCount: 0,
    enquiryCount: 0,
  },
  {
    id: "lst_003",
    title: "4 Bedroom Duplex in Wuse 2, Abuja",
    address: "Plot 7, Aminu Kano Crescent, Wuse 2",
    area: "Wuse 2",
    lga: "Municipal Area Council",
    state: "Abuja FCT",
    propertyType: "DUPLEX" as const,
    bedrooms: 4,
    bathrooms: 3,
    annualRent: 500000000,
    status: "PENDING_VERIFICATION" as const,
    isVerified: false,
    owner: mockAdminUsers[4],
    titleDocumentUrl: "/mock-title-doc.pdf",
    surveyPlanUrl: "/mock-survey.pdf",
    photos: [{ url: "/mock-property-3.jpg", order: 0 }],
    createdAt: new Date("2024-12-16"),
    viewCount: 0,
    enquiryCount: 0,
  },
];

export const mockOpenDisputes = [
  {
    id: "dsp_001",
    transactionId: "txn_001",
    transaction: {
      reference: "SR-2024-ABC12",
      rentAmount: BigInt(350000000),
      totalAmount: BigInt(387500000),
      escrowStatus: "DISPUTED" as const,
      tenant: mockAdminUsers[0],
      landlord: mockAdminUsers[1],
      listing: mockPendingListings[0],
    },
    raisedBy: mockAdminUsers[0],
    category: "NOT_AS_DESCRIBED" as const,
    description: "The property was described as fully furnished but was empty on arrival. No furniture as listed.",
    status: "OPEN" as const,
    outcome: null,
    resolution: null,
    resolvedAt: null,
    refundAmount: null,
    evidenceDeadline: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24h from now
    mediationDeadline: null,
    adjudicationDeadline: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 24h ago
    updatedAt: new Date(),
  },
  {
    id: "dsp_002",
    transactionId: "txn_002",
    transaction: {
      reference: "SR-2024-XYZ99",
      rentAmount: BigInt(180000000),
      totalAmount: BigInt(207000000),
      escrowStatus: "DISPUTED" as const,
      tenant: mockAdminUsers[3],
      landlord: mockAdminUsers[4],
      listing: mockPendingListings[1],
    },
    raisedBy: mockAdminUsers[3],
    category: "MAJOR_DEFECT" as const,
    description: "Roof is leaking badly. Water damage in 2 bedrooms. Property is not habitable.",
    status: "EVIDENCE_COLLECTION" as const,
    outcome: null,
    resolution: null,
    resolvedAt: null,
    refundAmount: null,
    evidenceDeadline: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h overdue
    mediationDeadline: new Date(Date.now() + 48 * 60 * 60 * 1000),
    adjudicationDeadline: null,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000), // 3 days ago
    updatedAt: new Date(),
  },
];

export const mockPlatformStats = {
  totalUsers: 1247,
  tenants: 893,
  landlords: 284,
  agents: 70,
  activeListings: 156,
  transactionsThisMonth: 34,
  transactionValueThisMonth: 12450000000, // in kobo
  escrowHeld: 8920000000,
  openDisputes: 7,
  verificationQueue: 12,
  platformRevenueThisMonth: 622500000, // 5% fees
  newSignupsToday: 8,
};

export const mockRecentSignups = mockAdminUsers.slice(0, 5);

export const mockPendingVerifications = [
  {
    type: "user" as const,
    id: "usr_003",
    name: "Emeka Nwosu",
    docType: "National ID",
    submittedAt: new Date("2024-12-18"),
    bvnMatch: "Partial",
  },
  {
    type: "user" as const,
    id: "usr_006",
    name: "Fatima Ibrahim",
    docType: "Voter's Card",
    submittedAt: new Date("2024-12-17"),
    bvnMatch: "Match",
  },
  {
    type: "listing" as const,
    id: "lst_001",
    name: "3 Bedroom Flat in Lekki Phase 1",
    docType: "Certificate of Occupancy",
    submittedAt: new Date("2024-12-18"),
    bvnMatch: null,
  },
  {
    type: "listing" as const,
    id: "lst_002",
    name: "Self-Contained Studio in Victoria Island",
    docType: "Deed of Assignment",
    submittedAt: new Date("2024-12-17"),
    bvnMatch: null,
  },
];
