export type MockListing = {
  id: string;
  title: string;
  slug: string;
  description: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  toilets: number;
  furnishingStatus: string;
  letType: string;
  propertyCondition: string;
  availableFrom: string;
  address: string;
  area: string;
  lga: string;
  state: string;
  landmark: string;
  neighbourhoodDescription?: string;
  annualRent: number;
  cautionDeposit: number;
  serviceCharge?: number;
  agencyFee?: number;
  paymentFrequencies: string[];
  amenities: string[];
  status: string;
  isVerified: boolean;
  viewCount: number;
  enquiryCount: number;
  photos: { id: string; url: string; caption?: string; order: number }[];
  owner: {
    id: string;
    firstName: string;
    lastName: string;
    landlordVerification?: { badgeTier: string } | null;
  };
  createdAt: string;
};

export const mockListings: MockListing[] = [
  {
    id: "mock_1",
    title: "Spacious 3-Bedroom Flat in Lekki Phase 1",
    slug: "spacious-3-bedroom-flat-lekki-phase-1-mock1",
    description:
      "A beautifully finished 3-bedroom flat in the heart of Lekki Phase 1. Features modern fittings, ample ventilation, and is in a serene gated estate with 24/7 security. Perfect for a family looking for comfort and safety.",
    propertyType: "FLAT",
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    furnishingStatus: "SEMI_FURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-06-01T00:00:00.000Z",
    address: "12 Admiralty Way, Lekki Phase 1",
    area: "Lekki Phase 1",
    lga: "Eti-Osa",
    state: "Lagos",
    landmark: "Near Lekki Phase 1 Roundabout",
    annualRent: 4500000,
    cautionDeposit: 4500000,
    serviceCharge: 500000,
    agencyFee: 450000,
    paymentFrequencies: ["ANNUAL", "BIANNUAL"],
    amenities: ["Generator", "Borehole", "Prepaid Meter", "Security", "Parking", "Fitted Kitchen"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 142,
    enquiryCount: 18,
    photos: [
      { id: "p1", url: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800", caption: "Living room", order: 0 },
      { id: "p2", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", caption: "Master bedroom", order: 1 },
      { id: "p3", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800", caption: "Kitchen", order: 2 },
    ],
    owner: { id: "u1", firstName: "Adaeze", lastName: "Okonkwo", landlordVerification: { badgeTier: "CERTIFIED" } },
    createdAt: "2026-04-15T10:00:00.000Z",
  },
  {
    id: "mock_2",
    title: "Modern 2-Bedroom Apartment in Maitama",
    slug: "modern-2-bedroom-apartment-maitama-mock2",
    description:
      "Tastefully furnished 2-bedroom apartment in the prestigious Maitama district of Abuja. Walking distance to major embassies and top restaurants. Comes with covered parking and 24/7 power supply.",
    propertyType: "FLAT",
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    furnishingStatus: "FULLY_FURNISHED",
    letType: "LONG_LET",
    propertyCondition: "NEW",
    availableFrom: "2026-05-20T00:00:00.000Z",
    address: "Plot 45, Nile Crescent, Maitama",
    area: "Maitama",
    lga: "Municipal Area Council",
    state: "Abuja FCT",
    landmark: "Near Transcorp Hilton Hotel",
    annualRent: 5000000,
    cautionDeposit: 5000000,
    serviceCharge: 600000,
    paymentFrequencies: ["ANNUAL"],
    amenities: ["Generator", "Borehole", "Central AC", "Security", "Parking", "Elevator", "Swimming Pool", "Gym"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 238,
    enquiryCount: 32,
    photos: [
      { id: "p4", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800", caption: "Exterior", order: 0 },
      { id: "p5", url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800", caption: "Living room", order: 1 },
    ],
    owner: { id: "u2", firstName: "Emeka", lastName: "Obi", landlordVerification: { badgeTier: "PROPERTY_VERIFIED" } },
    createdAt: "2026-03-20T08:00:00.000Z",
  },
  {
    id: "mock_3",
    title: "Self-Contained Studio in Yaba",
    slug: "self-contained-studio-yaba-mock3",
    description:
      "Cozy self-contained studio apartment in the heart of Yaba — Lagos' tech hub. Ideal for young professionals and students. Walking distance to UNILAG and major tech companies.",
    propertyType: "SELF_CONTAINED",
    bedrooms: 0,
    bathrooms: 1,
    toilets: 1,
    furnishingStatus: "UNFURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-06-15T00:00:00.000Z",
    address: "23 Herbert Macaulay Way, Yaba",
    area: "Yaba",
    lga: "Mainland",
    state: "Lagos",
    landmark: "Near Yaba Bus Stop",
    annualRent: 800000,
    cautionDeposit: 800000,
    paymentFrequencies: ["ANNUAL", "BIANNUAL", "QUARTERLY"],
    amenities: ["Prepaid Meter", "Borehole", "Security"],
    status: "UNVERIFIED_ACTIVE",
    isVerified: false,
    viewCount: 87,
    enquiryCount: 12,
    photos: [
      { id: "p6", url: "https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800", caption: "Room", order: 0 },
    ],
    owner: { id: "u3", firstName: "Tunde", lastName: "Adewale", landlordVerification: null },
    createdAt: "2026-04-28T14:00:00.000Z",
  },
  {
    id: "mock_4",
    title: "4-Bedroom Duplex in Ikoyi",
    slug: "4-bedroom-duplex-ikoyi-mock4",
    description:
      "Exquisite 4-bedroom duplex in the exclusive Ikoyi neighbourhood. Features a private garden, BQ, staff quarters, and high-end finishings throughout. Ideal for executives and diplomats.",
    propertyType: "DUPLEX",
    bedrooms: 4,
    bathrooms: 4,
    toilets: 5,
    furnishingStatus: "SEMI_FURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-07-01T00:00:00.000Z",
    address: "7 Glover Road, Old Ikoyi",
    area: "Old Ikoyi",
    lga: "Eti-Osa",
    state: "Lagos",
    landmark: "Near Ikoyi Club",
    annualRent: 8000000,
    cautionDeposit: 8000000,
    serviceCharge: 1200000,
    agencyFee: 800000,
    paymentFrequencies: ["ANNUAL"],
    amenities: ["Generator", "Borehole", "Prepaid Meter", "Central AC", "Fitted Kitchen", "BQ (Boys Quarter)", "Security", "Swimming Pool", "Parking"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 315,
    enquiryCount: 41,
    photos: [
      { id: "p7", url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800", caption: "Exterior", order: 0 },
      { id: "p8", url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800", caption: "Dining area", order: 1 },
    ],
    owner: { id: "u4", firstName: "Ngozi", lastName: "Eze", landlordVerification: { badgeTier: "CERTIFIED" } },
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "mock_5",
    title: "2-Bedroom Flat in Surulere",
    slug: "2-bedroom-flat-surulere-mock5",
    description:
      "Clean and spacious 2-bedroom flat in a quiet street in Surulere. The compound is well maintained with reliable water supply and dedicated parking space.",
    propertyType: "FLAT",
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    furnishingStatus: "UNFURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-06-01T00:00:00.000Z",
    address: "15 Adeniran Ogunsanya Street, Surulere",
    area: "Surulere",
    lga: "Surulere",
    state: "Lagos",
    landmark: "Near National Stadium",
    annualRent: 1200000,
    cautionDeposit: 1200000,
    paymentFrequencies: ["ANNUAL", "BIANNUAL"],
    amenities: ["Generator", "Borehole", "Prepaid Meter", "Security", "Parking"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 156,
    enquiryCount: 22,
    photos: [
      { id: "p9", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800", caption: "Living room", order: 0 },
    ],
    owner: { id: "u5", firstName: "Chidi", lastName: "Nwosu", landlordVerification: { badgeTier: "ID_VERIFIED" } },
    createdAt: "2026-04-10T11:00:00.000Z",
  },
  {
    id: "mock_6",
    title: "3-Bedroom Bungalow in Wuse 2",
    slug: "3-bedroom-bungalow-wuse2-mock6",
    description:
      "Well-maintained 3-bedroom bungalow in the desirable Wuse 2 area of Abuja. Located in a serene environment with easy access to major roads, markets, and government offices.",
    propertyType: "BUNGALOW",
    bedrooms: 3,
    bathrooms: 2,
    toilets: 3,
    furnishingStatus: "UNFURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-05-30T00:00:00.000Z",
    address: "22 Monrovia Street, Wuse 2",
    area: "Wuse 2",
    lga: "Municipal Area Council",
    state: "Abuja FCT",
    landmark: "Near Wuse Market",
    annualRent: 3000000,
    cautionDeposit: 3000000,
    paymentFrequencies: ["ANNUAL", "BIANNUAL"],
    amenities: ["Generator", "Borehole", "Prepaid Meter", "Security", "Parking", "Fitted Kitchen"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 198,
    enquiryCount: 27,
    photos: [
      { id: "p10", url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800", caption: "Exterior", order: 0 },
    ],
    owner: { id: "u6", firstName: "Fatima", lastName: "Abubakar", landlordVerification: { badgeTier: "PROPERTY_VERIFIED" } },
    createdAt: "2026-04-05T08:30:00.000Z",
  },
  {
    id: "mock_7",
    title: "1-Bedroom Flat in Ikeja GRA",
    slug: "1-bedroom-flat-ikeja-gra-mock7",
    description:
      "Neat 1-bedroom flat in the Ikeja Government Reserved Area. The estate offers 24/7 security, clean environment, and reliable power supply. Suitable for a single professional or couple.",
    propertyType: "FLAT",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    furnishingStatus: "UNFURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-06-01T00:00:00.000Z",
    address: "5 Mobolaji Bank-Anthony Way, Ikeja GRA",
    area: "Ikeja GRA",
    lga: "Ikeja",
    state: "Lagos",
    landmark: "Near MMIA Road",
    annualRent: 1500000,
    cautionDeposit: 1500000,
    paymentFrequencies: ["ANNUAL", "BIANNUAL", "QUARTERLY"],
    amenities: ["Generator", "Prepaid Meter", "Security", "Parking"],
    status: "UNVERIFIED_ACTIVE",
    isVerified: false,
    viewCount: 73,
    enquiryCount: 9,
    photos: [
      { id: "p11", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", caption: "Bedroom", order: 0 },
    ],
    owner: { id: "u7", firstName: "Yemi", lastName: "Soyinka", landlordVerification: null },
    createdAt: "2026-05-01T16:00:00.000Z",
  },
  {
    id: "mock_8",
    title: "5-Bedroom Detached House in Asokoro",
    slug: "5-bedroom-detached-house-asokoro-mock8",
    description:
      "Grand 5-bedroom detached house in the exclusive Asokoro district. The property sits on a large plot with well-manicured gardens, a large living space, and top-tier security. Close to the Aso Rock Villa.",
    propertyType: "DETACHED_HOUSE",
    bedrooms: 5,
    bathrooms: 5,
    toilets: 6,
    furnishingStatus: "FULLY_FURNISHED",
    letType: "LONG_LET",
    propertyCondition: "NEW",
    availableFrom: "2026-08-01T00:00:00.000Z",
    address: "3 Aso Drive, Asokoro",
    area: "Asokoro",
    lga: "Municipal Area Council",
    state: "Abuja FCT",
    landmark: "Near Hilton Hotel",
    annualRent: 12000000,
    cautionDeposit: 12000000,
    serviceCharge: 2000000,
    agencyFee: 1200000,
    paymentFrequencies: ["ANNUAL"],
    amenities: ["Generator", "Borehole", "Central AC", "Fitted Kitchen", "BQ (Boys Quarter)", "Security", "Swimming Pool", "Gym", "Parking", "Elevator", "Pet-friendly"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 489,
    enquiryCount: 56,
    photos: [
      { id: "p12", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", caption: "Exterior", order: 0 },
      { id: "p13", url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800", caption: "Living room", order: 1 },
    ],
    owner: { id: "u8", firstName: "Babatunde", lastName: "Fashola", landlordVerification: { badgeTier: "CERTIFIED" } },
    createdAt: "2026-02-14T10:00:00.000Z",
  },
  {
    id: "mock_9",
    title: "Room and Parlour in Alimosho",
    slug: "room-parlour-alimosho-mock9",
    description:
      "Clean room and parlour apartment in Alimosho. Affordable and suitable for a small family or couple on a budget. The compound has good water supply and a functional gate man.",
    propertyType: "ROOM_AND_PARLOUR",
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    furnishingStatus: "UNFURNISHED",
    letType: "LONG_LET",
    propertyCondition: "GOOD",
    availableFrom: "2026-06-01T00:00:00.000Z",
    address: "14 Shasha Road, Alimosho",
    area: "Shasha",
    lga: "Alimosho",
    state: "Lagos",
    landmark: "Near Shasha Market",
    annualRent: 450000,
    cautionDeposit: 450000,
    paymentFrequencies: ["ANNUAL", "QUARTERLY", "MONTHLY"],
    amenities: ["Borehole", "Security"],
    status: "UNVERIFIED_ACTIVE",
    isVerified: false,
    viewCount: 44,
    enquiryCount: 8,
    photos: [
      { id: "p14", url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800", caption: "Room", order: 0 },
    ],
    owner: { id: "u9", firstName: "Seun", lastName: "Kuti", landlordVerification: null },
    createdAt: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "mock_10",
    title: "Luxury Studio Apartment in Victoria Island",
    slug: "luxury-studio-victoria-island-mock10",
    description:
      "Premium studio apartment in one of Lagos' most prime addresses — Victoria Island. The apartment features smart-home technology, a fully equipped kitchen, and breathtaking city views.",
    propertyType: "STUDIO",
    bedrooms: 0,
    bathrooms: 1,
    toilets: 1,
    furnishingStatus: "FULLY_FURNISHED",
    letType: "SHORT_LET",
    propertyCondition: "NEW",
    availableFrom: "2026-05-25T00:00:00.000Z",
    address: "Plot 1234, Adeola Odeku Street, Victoria Island",
    area: "Victoria Island",
    lga: "Eti-Osa",
    state: "Lagos",
    landmark: "Near Eko Atlantic City",
    annualRent: 3600000,
    cautionDeposit: 600000,
    serviceCharge: 720000,
    agencyFee: 360000,
    paymentFrequencies: ["MONTHLY", "QUARTERLY"],
    amenities: ["Generator", "Central AC", "Fitted Kitchen", "Security", "Parking", "Elevator", "Swimming Pool", "Gym"],
    status: "VERIFIED_ACTIVE",
    isVerified: true,
    viewCount: 276,
    enquiryCount: 38,
    photos: [
      { id: "p15", url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800", caption: "Studio", order: 0 },
      { id: "p16", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", caption: "Kitchen", order: 1 },
    ],
    owner: { id: "u10", firstName: "Amina", lastName: "Garba", landlordVerification: { badgeTier: "CERTIFIED" } },
    createdAt: "2026-04-20T12:00:00.000Z",
  },
];
